// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XptoPortalApi.DataAcess;

namespace EFMigrate.Migrations
{
    [DbContext(typeof(MainContext))]
    [Migration("20200112175358_InitialMigrate")]
    partial class InitialMigrate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("XptoPortalApi.Models.App", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("XptoPortalApiApps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "DTI",
                            Url = "https://dtidigital.com.br/"
                        },
                        new
                        {
                            Id = 2,
                            Title = "wikipedia",
                            Url = "https://www.wikipedia.org/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
